site_name: Taller MkDocs
site_description: Sitio de documentación creado con MkDocs
site_author: Henmart02

theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.tabs.link

nav:
  - Inicio: index.md
  - Instalación: instalacion.md
  - Uso: uso.md
  - Acerca de: acerca.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: "#"
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets